Prefix: "§6AlexUtilities §b>> §r"
NoPlayer: "§4Nur Spieler können diesen Command benutzen!"
NoArgs: "§4Bitte verwende keine zusätzlichen Argumente!"
Success: "§aDer Command wurde erfolgreich ausgeführt!"