Prefix: "§6AlexUtilities §b>> §r"
NoPlayer: "§cNur Spieler können diesen Command benutzen!"
NoArgs: "§cBitte verwende keine zusätzlichen Argumente!"
Success: "§aDer Command wurde erfolgreich ausgeführt!"
Usage: "§cBitte benutze §b/"
JoinMessage: "§aDer Spieler §6%player% §ahat den Server betreten"
QuitMessage: "§4Der Spieler §6%player% §4hat den Server verlassen"