name: AlexUtilities
version: 4.0
main: com.github.cubealex.main.Main
author: GGAlex
website: https://www.github.com/GGAlex2578/AlexUtilities

commands:
  home:
    description: Teleportiert dich zu deinem Home Point
  sethome:
    description: Setzt deinen Home Point


